import { getScriptById, getVideoAssetById, listVideoAssets } from "../../repos";
import { artifactIdSchema, artifactsQuerySchema } from "../../schemas/apiSchemas";

const truncate = (text: string, maxLength: number) => {
  if (text.length <= maxLength) {
    return text;
  }
  return `${text.slice(0, maxLength - 3)}...`;
};

export interface ArtifactSummary {
  id: string;
  agent: string;
  type: "video_prompt";
  title: string;
  summary: string;
  thumbnail_url?: string | null;
  created_at: string | null;
}

export interface ArtifactDetail {
  id: string;
  storagePath: string;
  durationSeconds: number | null;
  metadata: {
    title: string;
    summary: string;
    beats: Array<{
      timestamp: string;
      visual: string;
      narration: string;
    }>;
    soundtrack?: string;
    transitions?: string;
  };
  thumbnailPath: string | null;
}

export const listArtifacts = async (rawQuery: Record<string, string | undefined>) => {
  const parsedQuery = artifactsQuerySchema.parse(rawQuery);
  const limit = parsedQuery.limit ?? 20;
  const assets = await listVideoAssets();

  const summaries: ArtifactSummary[] = [];

  for (const asset of assets.slice(0, limit)) {
    const script = asset.script_id ? await getScriptById(asset.script_id) : null;

    summaries.push({
      id: asset.asset_id,
      agent: "EditorAgent",
      type: "video_prompt",
      title: script?.hook ?? `Asset ${asset.asset_id}`,
      summary: script?.script_text
        ? truncate(script.script_text, 200)
        : "Video asset generated by ACE.",
      thumbnail_url: asset.thumbnail_path,
      created_at: asset.created_at ?? null,
    });
  }

  return summaries;
};

export const fetchArtifactDetail = async (artifactId: string) => {
  const validatedId = artifactIdSchema.parse(artifactId);
  const asset = await getVideoAssetById(validatedId);

  if (!asset) {
    return null;
  }

  const script = asset.script_id ? await getScriptById(asset.script_id) : null;
  const title = script?.hook ?? `Asset ${asset.asset_id}`;
  const summary =
    script?.script_text ?? "No script metadata is available for this artifact yet.";

  const detail: ArtifactDetail = {
    id: asset.asset_id,
    storagePath: asset.storage_path,
    durationSeconds: asset.duration_seconds ?? null,
    metadata: {
      title,
      summary,
      beats: [],
      soundtrack: undefined,
      transitions: undefined,
    },
    thumbnailPath: asset.thumbnail_path ?? null,
  };

  return detail;
};
